#!/bin/sh

# Copyright (c) 2018, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: ews-support@lairdtech.com

# overlay - mount the OverlayFS .
#

case $1 in

	stop)
		#Check for mounted overlayfs filesystem and unmount and cleanup
		if mountpoint -q /overlay 2>/dev/null
		then
			# Unmount the backing data store
			umount /overlay
		fi
		;;

	start)
		#Check for read only filesystem and mount an overlayfs if found
		if ! touch /etc/read-only 2>/dev/null
		then
			# Find our running ubiblock
			BLOCK=$(ls /dev/ubiblock*)
			OVERLAY=$((${BLOCK#*_} + 1))

			# Get the RW up in place
			mount -o noatime -t ubifs ubi0_${OVERLAY} /overlay

			# Get the overlay running
			mkdir -p /overlay/upper
			mkdir -p /overlay/work
			mount -o noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work -t overlay overlayfs:/overlay /mnt

			# Pivot the system
			mount -o noatime,move /proc /mnt/proc
			pivot_root /mnt /mnt/rom
			mount -o noatime,move /rom/sys /sys
			mount -o noatime,move /rom/dev /dev
			mount -o noatime,move /rom/tmp /tmp
			mount -o noatime,move /rom/overlay /overlay
		fi
		;;
esac
exit 0

