#!/bin/sh

# Copyright (c) 2016, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: ews-support@lairdtech.com

# lora packet forwarder init

start()
{
  echo "Starting lora packet forwarder"
  modprobe spi_atmel
  modprobe spidev

  # set the gateway EUI
  update_gwid /opt/lora/local_conf.json >/dev/null

  # start the concentrator
  reset_lgw start

  # brind up the packet forwarder
  cd /opt/lora/
  lora_pkt_fwd >/var/log/lora_pkt_fwd 2>&1 &
}

stop()
{
  echo "Stopping lora packet forwarder"
  killall lora_pkt_fwd 2>/dev/null

  # hold the concentrator in reset
  reset_lgw stop

  true
}


case $1 in
  stop)
    stop
    ;;
  start)
    start
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {stop|start|restart}"
    false
esac

exit $?
