ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_SUPPLICANT_BINARIES_VERSION = $(call qstrip,$(BR2_PACKAGE_LRD_RADIO_STACK_VERSION_VALUE))
SUMMIT_SUPPLICANT_BINARIES_SOURCE =
SUMMIT_SUPPLICANT_BINARIES_LICENSE = BSD-3-Clause

ifneq ($(BR2_PACKAGE_LAIRD_OPENSSL_FIPS_BINARIES),)
SUMMIT_SUPPLICANT_BINARIES_TYPE1 = _fips
else ifneq ($(BR2_PACKAGE_LIBOPENSSL_1_0_2),)
SUMMIT_SUPPLICANT_BINARIES_TYPE1 = _openssl_1_0_2
else
SUMMIT_SUPPLICANT_BINARIES_TYPE1 =
endif

ifneq ($(BR2_arm),)
ifneq ($(BR2_ARM_EABIHF),)
SUMMIT_SUPPLICANT_BINARIES_TYPE2 = -arm-eabihf
else
SUMMIT_SUPPLICANT_BINARIES_TYPE2 = -arm-eabi
endif
else ifneq ($(BR2_aarch64),)
SUMMIT_SUPPLICANT_BINARIES_TYPE2 = -aarch64-eabihf
else
$(error "Unknown architecture")
endif

SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS = summit_supplicant$(SUMMIT_SUPPLICANT_BINARIES_TYPE1)$(SUMMIT_SUPPLICANT_BINARIES_TYPE2)-$(SUMMIT_SUPPLICANT_BINARIES_VERSION).tar.bz2

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  SUMMIT_SUPPLICANT_BINARIES_SITE = https://files.devops.rfpros.com/builds/linux/summit_supplicant/laird/$(SUMMIT_SUPPLICANT_BINARIES_VERSION)
else
  SUMMIT_SUPPLICANT_BINARIES_SITE = https://github.com/LairdCP/wb-package-archive/releases/download/LRD-REL-$(SUMMIT_SUPPLICANT_BINARIES_VERSION)
endif

define SUMMIT_SUPPLICANT_BINARIES_INSTALL_TARGET_CMDS
	tar -xjf $($(PKG)_DL_DIR)/$(SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch
endef

endif

$(eval $(generic-package))
