#!/bin/sh
# logging services
#

case $1 in

  stop)
    echo -n "Stopping logging services:"
    
    killall event_mon 2>/dev/null

    killall syslogd \
    && echo -n " syslogd"
    
    killall klogd \
    && echo -n " klogd"
    
    echo
    ;;
	
  start)
    echo -n "Starting logging services:"
    
    /sbin/syslogd -D -C32 -m0 \
    && echo -n " syslogd"
    
    /sbin/klogd \
    && echo -n " klogd"
    
    echo
    event_mon --output logging &
    ;;
	
  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: $0 {stop|start|restart}"
    exit 1
esac

exit 0
