#!/bin/sh

# Copyright (c) 2016, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

# Provides support for USB Mass Storage and Flash Devices.

# bus identifiers
ehci_bus=/dev/bus/usb/002/001
ohci_bus=/dev/bus/usb/001/001

rv=1
case $1 in

	stop)
		echo -e "Stopping USB host-mode"

		# this will not be effective if still setting up,
		# and thus... usb-storage will still be in use
		umount /media/usb* 2>/dev/null

		modprobe -r usb-storage

		if grep -sq 'smart[BS][AS]' /proc/[0-9]*/comm
		then
			echo "Warning: SmartBASIC is still running"
		fi
		modprobe -r ohci_at91
		modprobe -r ehci_atmel
		modprobe -r usb-storage
		rv=$?
	;;

	start)
		echo -e "Starting USB host-mode"
		[ ! -d /sys/class/net/usb0 ] \
		|| { echo "  Warning: USB is already in device mode."; }

		modprobe ehci_atmel
		{ read -rst2 x < ${ehci_bus}; } 2>/dev/null
		# enumerate and provide upto 2s delay - don't unload

		modprobe ohci_at91
		{ read -rst3 x < ${ohci_bus}; } 2>/dev/null
		# enumerate and provide upto 3s delay - don't unload

		modprobe usb-storage
		rv=$?
	;;

	status)
		echo -n "ehci_hcd"
		if grep -q ehci_hcd /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		echo -n "ehci_atmel"
		if grep -q ehci_atmel /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		echo -n "ohci_hcd"
		if grep -q ohci_hcd /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		echo -n "ohci_at91"
		if grep -q ohci_at91 /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		cat ${ohci_bus} >/dev/null 2>&1
		echo -n usb_storage
		if grep -q usb_storage /proc/modules && rv=$?
		then
			grep -q usb /proc/mounts && echo " mounted" || echo " unmounted"
			echo \ \ Attached:
			grep -o "[ ]\+[0-9]\+[ ][vs]d.*" /proc/partitions || echo -e "\t  0 ..."
		else
			echo " n/a"
		fi
	;;

	*)
		echo "Usage: $0 {stop|start|status}"
	;;
esac
exit $rv