#!/bin/sh

# Copyright (c) 2016, Laird Connectivity
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

# Provides support for USB Mass Storage and Flash Devices.

# bus identifiers
ehci_bus=/dev/bus/usb/002/001
ohci_bus=/dev/bus/usb/001/001

rv=0
case $1 in

	stop)
		echo -e "Stopping USB host-mode"

		modprobe -r ohci_at91
		modprobe -rq ehci_atmel

		sleep 1

		modprobe -r usb-storage
		rv=$?
	;;

	start)
		echo -e "Starting USB host-mode"
		[ ! -d /sys/class/net/usb0 ] || \
			echo "  Warning: USB is already in device mode."

		modprobe -qa ehci_atmel ohci_at91

		modprobe usb-storage
		rv=$?

		modprobe -q vfat
	;;

	status)
		echo -n "ehci_hcd"
		if grep -q ehci_hcd /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		echo -n "ehci_atmel"
		if grep -q ehci_atmel /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		echo -n "ohci_hcd"
		if grep -q ohci_hcd /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		echo -n "ohci_at91"
		if grep -q ohci_at91 /proc/modules
		then
			echo " loaded"
		else
			echo " n/a"
		fi
		cat ${ohci_bus} >/dev/null 2>&1
		echo -n usb_storage
		if grep -q usb_storage /proc/modules && rv=$?
		then
			grep -q usb /proc/mounts && echo " mounted" || echo " unmounted"
			echo \ \ Attached:
			grep -o "[ ]\+[0-9]\+[ ][vs]d.*" /proc/partitions || echo -e "\t  0 ..."
		else
			echo " n/a"
		fi
	;;

	*)
		echo "Usage: $0 {stop|start|status}"
	;;
esac
exit $rv
