#!/bin/sh

# Copyright (c) 2016, Laird Connectivity
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

# wifi - wifi driver bring up

WIFI_PREFIX=wlan
WIFI_DRIVER=ath6kl_sdio
WIFI_MODULE=ath/ath6kl/ath6kl_sdio.ko
WIFI_KMPATH=/lib/modules/`uname -r`/kernel/drivers/net/wireless

case "$1" in
start)
	modprobe cfg80211
	modprobe ath6kl_core
        modprobe $WIFI_DRIVER
	ip link set dev wlan0 up 2>&1
	;;

stop)
	ip addr flush dev wlan0
	ip link set dev wlan0 down 2>&1
	modprobe -r $WIFI_DRIVER
	;;

restart)
	stop
	start
	;;

*)
	echo "Usage: /etc/init.d/S40wifi {start|stop|restart}"
	exit 1
	;;
esac
exit 0

