#!/bin/sh
# inetd - super server initialization (nonblocking)
#
# For enabled services in /etc/inetd.conf,  a pre-check is performed for each
# daemon's init-script successfully found in /etc/init.d/opt/.
#
# Each init-script should have a 'check)' handler to prepare its service.
# This allows using TCPwrappers to respond fast to a requested protocol.
# jon.hefling@lairdtech.com

rcS_log=${rcS_log:-/dev/null}

log() {
  echo "$@" >>$rcS_log
}

inetd_daemon_check() {
  while read -r a1 a2 a3 a4 a5 a6 a7
  do
    # parse daemon-executable, daemon-name, daemon-init-script
    # via args list from the inetd.conf file
    #
    [ -z $a1 ] && continue
    [ "${a1}" == "#" ] && continue
    [ "${a1:0:2}" == "#!" ] && continue

    srv=$a1
    daemon_exec=$a6
    daemon_name=${daemon_exec##*/}
    daemon_init=/etc/init.d/opt/S??${daemon_name}
    #
    # check if this service daemon can be enabled
    [ ${daemon_name:0:1} == "#" ] && { log "  $srv is disabled"; continue; }
    [ -x $daemon_exec"" ] || { log "  $srv is n/a, missing"; continue; }
    [ -x $daemon_init"" ] || { log "  $srv check is n/a"; continue; }
    #
    # wait on any net-init firstly, to avoid conflicts due to excessive load
    # run an enabled daemon-init-script to perform a pre-check in background
    # ( this allows the service to be started quickly when actually needed )
    # and add each daemon-init pid to list, to wait on before starting inetd
    #
    ( wait $net_init_pids; $daemon_init check >>$rcS_log; )&
    srv_init_pids=$srv_init_pids\ $!
    log "  $daemon_init check - $!"
    echo -n " $srv"

  done < /etc/inetd.conf
}

# find any network and bridge init-script pids
let net_init_pids=$( ps |sed -n '/[S]..[nb][er][ti][wd][og][re]/s/^\ *\([0-9]\+\).*/\1/p' )+0

export inetd_=^
case $1 in

  reload)
    echo "Reloading inetd configuration."
    killall -s HUP inetd
    ;;
    
  restart)
    $0 stop
    $0 start
    ;;
    
  start)
    echo -n "Checking inetd services..."
    # the config file is required
    if [ ! -f /etc/inetd.conf ]
    then
      echo -e "\n  file /etc/inetd.conf is missing"
      exit 1
    fi
    inetd_daemon_check
    echo
    #
    # wait in background to run super server 
    ( wait $srv_init_pids; /usr/sbin/inetd && echo "  inetd ready" >>$rcS_log )&
    ;;
    
  stop)
    echo "Stopping inetd."
    killall inetd 2>/dev/null
    ;;

  *)
    echo "Usage: $0 {stop|start|restart|reload}"
    ;;
esac
exit 0
