#!/bin/ash

# Copyright (c) 2015, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

# lighttpd - webserver init
# This init-script includes support for inetd.
#
# Usage:
# ./S??lighttpd {stop|start|restart|status|check}
#
# Invocation:
# ./S??lighttpd start [/etc/lighttpd/lighttpd.conf]
#


status() {
  echo "+ ps ax -opid,args"
  ps ax -opid,args |grep -e"[^0-9]lighttp[d]" -e"php[-]"
}

start() {
  if ! status >/dev/null
  then
    test -x /usr/sbin/lighttpd \
      || { echo "  lighttpd n/a"; exit 1; }

    echo "Starting LigHTTPd"
    /usr/sbin/lighttpd -f ${lighttpd_conf} \
      >/var/log/lighttpd 2>&1
  fi
}

stop() {
  if status >/dev/null
  then
    echo "Stopping LigHTTPd"
    killall lighttpd 2>/dev/null
    killall php-cgi 2>/dev/null
  fi
  true
}

# Note: invocation is start [conf]
# The config file can be a symlink or passed-in.
lighttpd_conf=${2:-/etc/lighttpd/lighttpd.conf}

case $1 in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  status)
    status
    ;;

  check) ## required for S??inetd pre-checking
    test -s ${lighttpd_conf} \
      || { echo "  $lighttpd_conf n/a"; return 2; }

    /usr/sbin/lighttpd -tf ${lighttpd_conf} |grep -q 'Syntax OK' \
    || { echo "  $lighttpd_conf error"; false; }
    ;;

  *)
    echo "Usage: ${0##*/} {stop|start|restart|status|check}"
    false
esac

exit $?
