#!/bin/ash

# Copyright (c) 2018, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: CS-Support@lairdtech.com

show_usage_info() {
	echo 'This utility is used to update the hostname system wide'
	echo 'Usage: /usr/sbin/hostname_update set <new hostname>'
}

update_hostname(){
	if [ ! -z "$1" ];
	then
		echo $1 > /proc/sys/kernel/hostname
		sed -i 's/127.0.0.1.*/127.0.0.1\t'"$1"'/g' /etc/hosts
		echo $1 > /etc/hostname
	fi
}


case $1 in
  set)
    update_hostname "$2"
  ;;
  *)
    show_usage_info
  ;;
esac