#!/bin/sh
# usbhost - init for wb45n
# Provides host-mode support for USB Mass Storage and Flash Devices.


ohci_bus=/dev/bus/usb/001/001

rv=1
case $1 in

  stop)
    echo -e "Disabling USB host-mode for Mass Storage"
    
    # this will not be effective if still setting up,
    # and thus... usb-storage will still be in use
    umount /media/usb* 2>/dev/null
    
    modprobe -r usb-storage
    rv=$?
    ;;

  start)
    echo -e "Enabling USB host-mode for Mass Storage"
    
    [ ! -d /sys/class/net/usb0 ] \
    || { echo "  Error: USB is already in device mode."; exit 1; }

    modprobe ohci-hcd 
    { read -rst1 x < ${ohci_bus}; } 2>/dev/null
      # enumerate and provide upto 1s delay
    
    modprobe usb-storage
    rv=$?
    ;;

  status)
    cat ${ohci_bus} >/dev/null 2>&1
    echo -n STATUS=
    if grep -q usb_storage /proc/modules && rv=$?
    then
      grep -q usb /proc/mounts && echo mounted || echo unmounted
      echo \ \ Attached:
      grep -o "[ ]\+[0-9]\+[ ][vs]d.*" /proc/partitions || echo -e "\t  0 ..."
    else
      echo n/a
    fi
    ;;

  *)
    echo "Usage: $0 {stop|start|status}"
    ;;
esac
exit $rv
