#!/bin/sh
# bluetooth - init for wb45n
# Creates or removes the host control interface.

await_interface() {
  # args: <class/iface> [<milliseconds>]
  let n=0 w=${2:-0}
  while : wait increments of 10ms for address
  do
    { mac=; read -rs mac </sys/class/${1}/address; } 2>/dev/null
    test "${mac/??:??:??:??:??:??/up}" == "up" && break
    test $n -lt $w && let n+=10 && usleep 9999 || break
  done
  test $n -ge 10 && echo -en "  ...waited ${n}ms${mac:+\n}"
  test -n "$mac" && rv=0 || rv=1
  return $rv
}

start() {
  echo "Enabling Bluetooth"
  #
  # loadable kernel module support for wb45:
  #  ohci-hcd
  #   bnep
  #   rfcomm
  #   hidp
  #    hid - hidp
  #   btusb
  #    bluetooth - bnep, rfcomm, hidp, btusb
  #
  modprobe ohci-hcd
  modprobe btusb
  modprobe hidp
  modprobe rfcomm
  modprobe bnep

  # must wait for ohci enumeration, or will get hci init error
  await_interface bluetooth/hci0 2000 \
  || { echo "  ...error, host control interface n/a"; return; }

  hciconfig hci0 up
  rv=$?
}

stop() {
  echo "Disabling Bluetooth"

  await_interface bluetooth/hci0 \
  && hciconfig hci0 down \
  || echo "  ...already disabled"

  # don't unload ohci-hcd, as other things might be using it
  modprobe -r btusb hidp rfcomm bnep
  rv=$?
}

rv=1
case $1 in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  status)
    echo -n STATUS=
    if await_interface bluetooth/hci0
    then
      echo `hciconfig |sed '/[UD][PO][WN]*/!d;s/ .*//;y/UPDOWNRIG/updownrig/'`
      echo CLASS=`cat /sys/class/bluetooth/hci0/class`
      echo NAME=\"`cat /sys/class/bluetooth/hci0/name`\"
      echo MAC=$mac
    else
      echo n/a
    fi
    ;;

  *)
    echo "Usage: $0 stop|start|status|restart}"
    ;;
esac
exit $rv
