#!/bin/sh
# g_ether - init for wb40n
#
# This init only loads/unloads the hw-phy gadget driver for a USB interface.
# Configuration is handled via helpers in /etc/network. See the /e/n/i file.

# the iface name
USB_IF=usb0


checkinterface() {
  # args: <deciseconds> <iface>
  let n=$1 
  ds='busybox usleep 100000'
  until grep -so "$2" /proc/net/dev || ! let n-=1; do echo -en .; $ds; done
  [ $n -le 0 ] && return 1 || return 0
}

start() {
  echo -e "Enabling USB gadget ethernet \c"

  modprobe g_ether
  
  # await 1.2 seconds for interface
  checkinterface 12 $USB_IF \
  || { echo -e "\n  ...driver error, interface $USB_IF n/a"; exit 1; }
  
  ifconfig $USB_IF up
}

stop() {
  echo "Disabling USB gadget ethernet"
  ifconfig $USB_IF 0.0.0.0 2>/dev/null
  ifconfig $USB_IF down 2>/dev/null
  
  grep -q ^g_ether /proc/modules && modprobe -r g_ether
}

case $1 in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "$0 $@ -- error"
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
