#!/bin/sh
# enable/disable bluetooth functionality for wb40n

WIFI_MACADDR=/etc/summit/wifi_interface


bt_start() {
  echo "Enabling Bluetooth..."

  test -x /usr/bin/patchram || { echo "  patchram missing, aborted"; exit 1; }

  ps |grep -q "[p]atchram" && { echo "  already enabled!"; exit 1; }

  # take BT out of reset
  echo 107 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio107/direction
  echo 1 > /sys/class/gpio/gpio107/value

  # load BT kernel modules
  modprobe hci_uart
  modprobe bnep
  modprobe rfcomm
  modprobe hidp
  modprobe atmel-ssc

  #/usr/sbin/hciattach /dev/ttyS3 bcm2035 921600

  # get BT config values
  source /etc/summit/bluetooth.conf

  # get WL mac address, and ensure it is valid
  wlmac=$( grep -s ..:..:..:..:..:.. $WIFI_MACADDR )
  wlmac=${wlmac:-00:17:23:00:00:00}
  # set btmac to wlmac+1
  maca=${wlmac:9}
  macx=0x${maca//:/}
  let macx+=1
  let macx\&=0xffffff
  macx=`printf "%06x" $macx`
  btmac=${wlmac:0:8}:${macx:0:2}:${macx:2:2}:${macx:4:2}

  # dev/test
  #btbaudrate=921600
  #btpatchram=/etc/summit/firmware/BCM4329B1_002.002.023.0924.1027.hcd

  # apply BT settings
  patchram --enable_hci --baudrate $btbaudrate \
   --patchram $btpatchram --bd_addr $btmac /dev/ttyS3 &

  # enter BT sleep mode
  #/usr/hcitool cmd 0x3f 0x27 0x1 0x10 0x10 0x0 0x0 0x0 0x1 0x0

  sleep 2
}

bt_stop() {
  echo "Disabling Bluetooth..."
  killall patchram 2>/dev/null
  modprobe -r atmel-ssc hidp rfcomm bnep hci_uart
  # put BT in reset
  echo 0 > /sys/class/gpio/gpio107/value
  echo 107 > /sys/class/gpio/unexport
}

#trap "" 1 15

case "$1" in
  stop)
    bt_stop
    ;;

  start)
    bt_start
    ;;

  restart)
    bt_stop
    bt_start
    ;;

  *)
    echo "Usage: $0 stop|start|restart}"
    exit 1
    ;;
esac

exit 0
