#!/bin/sh
case "$1" in
  start)
    mkdir -p /var/cache/tlsdated/
    tlsdated -U 2>/dev/null &
    ;;
  stop)
    killall tlsdated 2>/dev/null
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
