#!/bin/sh

# Copyright (c) 2018, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

start()
{
  echo "Starting easycwmpd"

  # configure the required environment vars
  export UCI_CONFIG_DIR="/etc/config/"
  export UBUS_SOCKET="/var/run/ubus.sock"
  # start ubus in the background
  /usr/sbin/ubusd -s $UBUS_SOCKET &

  UCI_SET="/usr/bin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set"
  UCI_GET="/usr/bin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} get"
  UCI_COMMIT="/usr/bin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} commit"

  # configure the dynamic device information
  local val oval
  local change=0

  val="laird"
  oval=`$UCI_GET easycwmp.@device[0].manufacturer`
  [ -n "$val" -a "$val" != "$oval" ] && { $UCI_SET easycwmp.@device[0].manufacturer="$val"; change=1; }

  val="sentrius"
  oval=`$UCI_GET easycwmp.@device[0].product_class`
  [ -n "$val" -a "$val" != "$oval" ] && { $UCI_SET easycwmp.@device[0].product_class="$val"; change=1; }

  val="$REG"
  oval=`$UCI_GET easycwmp.@device[0].hardware_version`
  [ -n "$val" -a "$val" != "$oval" ] && { $UCI_SET easycwmp.@device[0].hardware_version="$val"; change=1; }

  . /etc/os-release
  val=${VERSION_ID}
  oval=`$UCI_GET easycwmp.@device[0].software_version`
  [ -n "$val" -a "$val" != "$oval" ] && { $UCI_SET easycwmp.@device[0].software_version="$val"; change=1; }

  val=`cat "/etc/hostname"`
  oval=`$UCI_GET easycwmp.@device[0].serial_number`
  [ -n "$val" -a "$val" != "$oval" ] && { $UCI_SET easycwmp.@device[0].serial_number="$val"; change=1; }

  val=`echo "C0EE40"`
  oval=`$UCI_GET easycwmp.@device[0].oui`
  [ -n "$val" -a "$val" != "$oval" ] && { $UCI_SET easycwmp.@device[0].oui="$val"; change=1; }

  [ "$change" = "1" ] && $UCI_COMMIT easycwmp

  # execute the easycwmp daemon in the background
  /usr/sbin/easycwmpd -f -b 2>&1 >/dev/null &
}

stop()
{
  echo "Stopping easycwmpd"
  killall easycwmpd
  killall ubusd

  true
}


case $1 in
  stop)
    stop
    ;;
  start)
    start
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {stop|start|restart}"
    false
esac

exit $?
