#!/usr/bin/env bash

LEGAL_MANIFEST_CSV_HOST=$1
LEGAL_MANIFEST_CSV_TARGET=$2
SBOM_HOST=$3
SBOM_TARGET=$4

awk -F "\"*,"\"* '{print $1"|"$2}' ${LEGAL_MANIFEST_CSV_HOST} > ${SBOM_HOST}
awk -F "\"*,"\"* '{print $1"|"$2}' ${LEGAL_MANIFEST_CSV_TARGET} > ${SBOM_TARGET}
sed -i 's/"/|/' ${SBOM_HOST}; sed -i 's/"/|/' ${SBOM_TARGET}
