#! /bin/sh
# Script to generate downlaod NVD-CVE database

CACHE_DBS=$1/dbs
year=`date +"%Y"`
NIST_URL="https://nvd.nist.gov/download"

status_report(){
		echo -n "####"
}

#download nvd-cve files
download_files(){
	wget --tries=3 --connect-timeout=10  --quiet $NIST_URL/nvdcve-$1.xml.gz --directory-prefix=$CACHE_DBS
	if [ $? -ne 0 ]; then
		echo -n " ] [ Download Failed ]"
		echo
		exit 1
	fi
	gunzip --quiet $CACHE_DBS/nvdcve-$1.xml.gz
}

update_dbs(){
echo -n "[ "
#check if dir exist
	if [ -d $CACHE_DBS ]  && [ ! "$(ls -A $CACHE_DBS)" ]; then
		for i in $(seq -f "%04g" 2002 $year)
		do
			download_files $i
			status_report
		done
		echo -n " ] [ Done ]"
	elif [ -d $CACHE_DBS ] && [ "$(ls -A $CACHE_DBS)" ]; then
		for i in $(seq -f "%04g" 2002 $year)
		do
			if [ ! -e $CACHE_DBS/nvdcve-$i.xml ]; then
				download_files $i
				status_report
			else
				status_report
			fi
		done

		#update the current year again
		if [ -e $CACHE_DBS/nvdcve-$year.xml ]; then
			rm $CACHE_DBS/nvdcve-$year.xml
		fi
		download_files $year
		echo -n " ] [ Done ]"
	else
		mkdir -p $CACHE_DBS
		for i in $(seq -f "%04g" 2002 $year)
		do
			download_files $i
			status_report
		done
		echo -n " ] [ Done ]"
	fi
	echo
}


####main
echo "Caching NVD-CVE Database Files [ Started ]"
update_dbs && echo "Finished NVD-CVE Database [ Done ]"
