#! /bin/bash
# Script to generate downlaod NVD-CVE database

CACHE_DBS=$1
BUILD_CVE_DBS=$2
year=$(date +"%Y")
NIST_URL=https://nvd.nist.gov/download/nvdcve-{2002..$year}.xml.zip
NIST_FILE=$CACHE_DBS/nvdcve-{2002..$year}.xml.zip

echo "Caching NVD-CVE Database Files [ Started ]"

wget -N --tries=3 --connect-timeout=10 --quiet --directory-prefix=$CACHE_DBS $(eval "echo $NIST_URL")

if [ $? -ne 0 ]; then
  for i in $(eval "echo $NIST_FILE"); do
    if [ ! -f $i ]; then
      echo " [ Download Failed $i ]"
      exit 1
    else
      echo "[ Download Failed $i, using cached file ]"
    fi
  done
fi

unzip -qod $BUILD_CVE_DBS "$CACHE_DBS/nvdcve-*.xml.zip"

if [ $? -ne 0 ]; then
  echo " [ Unzip Failed nvdcve-*.xml.zip ]"
  exit 1
fi

echo "Finished NVD-CVE Database [ Done ]"
