#!/bin/ash

# Copyright (c) 2015, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: ews-support@lairdtech.com

# conf-resolv
# Maintains symlinked copy of '/etc/resolv.conf' as '/tmp/resolv.conf'.
#
# Usage:
#   conf-resolv [chk]
#   conf-resolv [add] <iface> [search|nameserver <address>...]
#   conf-resolv [del] <iface> [search|nameserver <address>]
#
#   ..w/o command, then just dump resolv.conf file


x_chk() {
  if [ ! -h /etc/resolv.conf ]
  then
    # move if is a regular file
    test -f /etc/resolv.conf ] \
      && mv /etc/resolv.conf /tmp

    # install symlink
    ln -s /tmp/resolv.conf /etc/resolv.conf
  fi
  test -s /tmp/resolv.conf \
    || printf "\n" >/tmp/resolv.conf

  grep -q "$self" /tmp/resolv.conf \
    || sed "1i### Edited/maintained by $self." -i /tmp/resolv.conf

  grep -cq "^nameserver ..." /tmp/resolv.conf \
    || sed "2inameserver 8.8.8.8" -i /tmp/resolv.conf

  grep -q timeout:. /tmp/resolv.conf \
    || printf "options timeout:3\n" >>/tmp/resolv.conf

  true
}

x_add() {
  # check if valid nameserver
  nslookup $1 $1 >/dev/null \
    || return 1
  # and insert if not there
  grep -q "^nameserver $1" /tmp/resolv.conf \
    && return 1 \
    || sed "2inameserver $1" -i /tmp/resolv.conf
  return $?
}

x_del() {
  sed -i "/^nameserver $1/d" /tmp/resolv.conf
}

self=${0##*/}
cmd=$1
iface=$2
shift 2
case $cmd in
  '') ## output the resolv.conf
    cat /tmp/resolv.conf
    ;;

  -c|chk) ## check resolv.conf
    x_chk
    ;;

  -a|add) ## create entry for iface
    x_chk
    while [ -n "$1" ]
    do
      case $1 in
        domain)
          shift
          ;;
        search)
          shift
          if [ -n "$1" ]
          then
            grep -q "^search $1" /tmp/resolv.conf \
              || sed "2isearch $1" -i /tmp/resolv.conf
            shift
          fi
          ;;
        nameserver)
          shift
          for x in $1 $2 $3; do shift; x_add $x && break; done
          ;;
        *)
          shift
      esac
    done
    ;;

  -d|del) ## remove entry
    x_del $2
    ;;

  -h) ## show usage
    sed '2,/^$/!d' $0
esac
