#!/bin/sh

# Copyright (c) 2015, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

# bridge init-script
# For exclusive bridge-mode setup only.
# Note - This script will conflict with other networking setups.

trap "" 1 15
xc=\\033[1K\\\r

ETH_WIRED=eth0
ETH_WIFI=wlan0
BRIDGE=br0

[ -x /usr/sbin/brctl ] || { echo "brctl n/a"; exit 1; }
[ -x /sbin/ebtables ] || { echo "ebtables n/a"; exit 1; }

waitfor_interface() {
  delay='usleep 200000'
  let n=0
  echo -en \ \ ${1}..
  while ! grep -q ${1} /proc/net/dev
  do
    echo -en .
    [ 10 -gt $n ] || { echo N/A; return 1; }
    let n+=1
    $delay
  done
  $delay
  echo -en $xc
  return 0
}
waitfor_initscript() {
  delay='usleep 1000000'
  let n=0
  # if script active, then wait for it to finish 
  while ps |grep -q "S[0-9][0-9]${1}"
  do
    [ 0 -eq $n ] && echo \ \ waiting for $1...
    #echo -en .
    let n+=1
    $delay
  done
  #echo -en $xc 
  killall udhcpc dhclient dhcpcd dhcp3-client 2>/dev/null
}

start() {
  echo Starting bridged network support.

  # wait on S??network* script if warranted
  $nwon && waitfor_initscript network

  waitfor_interface $ETH_WIRED || exit 1
  ifconfig $ETH_WIRED up || { echo $ETH_WIRED error; exit 1; }
  ifconfig $ETH_WIRED 0.0.0.0 || { echo $ETH_WIRED cfg error; exit 1; }
	
  waitfor_interface $ETH_WIFI || /etc/network/wireless.sh start || exit 1
  ifconfig $ETH_WIFI 0.0.0.0 || { echo $ETH_WIRED cfg error; exit 1; }
  
  brctl addbr $BRIDGE
  brctl stp $BRIDGE off
  brctl setfd $BRIDGE 0
  brctl addif $BRIDGE $ETH_WIRED $ETH_WIFI
  echo \ \ enablng $BRIDGE
  if ifconfig $BRIDGE up
  then
    echo 1 > /proc/sys/net/ipv4/conf/all/proxy_arp
    echo 1 > /proc/sys/net/ipv4/ip_forward

    read braddr < /sys/class/net/$BRIDGE/address
    ebtables -A FORWARD --in-interface $ETH_WIFI --protocol 0x0806 --arp-mac-src $braddr -j DROP
    # prevent ARP packets from interfering w/DHCP by dropping the bridge's mac address

    ebtables -t nat -F PREROUTING
    ebtables -t nat -F POSTROUTING
    ebtables -t broute -F BROUTING
    ebtables -t nat -A PREROUTING  --in-interface $ETH_WIFI -j arpnat --arpnat-target ACCEPT
    ebtables -t nat -A POSTROUTING --out-interface $ETH_WIFI -j arpnat --arpnat-target ACCEPT
    ebtables -t broute -A BROUTING --in-interface $ETH_WIFI --protocol 0x888e -j DROP
  else
    echo \ \ bridge setup failed; exit 1
  fi
  brctl show
}

stop() {
  echo Stopping bridged network support.
  ebtables -t nat -F
  ebtables -F
  echo \ \ disabling $BRIDGE
  ifconfig $BRIDGE down 2>/dev/null
  brctl delbr $BRIDGE
}

# optional -x is no-wait-on-network 
nwon=true
[ "$1" == "-x" ] && nwon=false && shift

case $1 in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "Usage: $0 {stop|start|restart}"
    exit 1
    ;;
esac
exit 0

