#!/bin/sh

trap "" 1
trap "" 15

PPP_SERIAL_INTERFACE=/dev/ttyS1
PPP_SERIAL_RATE=230400

start() {
  echo "Starting pppd"
  modprobe ppp_generic
  modprobe ppp_async
  /usr/sbin/pppd \
   192.168.0.1:192.168.0.2 \
   $PPP_SERIAL_INTERFACE \
   $PPP_SERIAL_RATE \
    > /dev/null &
}

stop() {
  echo "Stopping pppd"
  killall -9 pppd
  rmmod ppp_async
  rmmod crc_ccitt
  rmmod ppp_generic
  rmmod slhc
}

case "$1" in
  
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
