#!/bin/sh 

# Copyright (c) 2015, Laird Connectivity
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

# tftpd init-script
# supports inetd

pre_check() {
  test -x $tftpd || { echo "$tftpd missing"; exit 1; }
  
  [ ! -d /var/run/tftpd ] && mkdir -p /var/run/tftpd
  [ ! -f /var/log/wtmp ] && touch /var/log/wtmp
}

tftpd=/usr/sbin/tftpd

case "$1" in
  stop)
    echo "Stopping tftp daemon"
    killall tftpd 2>/dev/null
    ;;

  start)
    echo "Starting tftp daemon"
    [ -z "$rcS_" ] && pre_check
    $tftpd
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  check)
    pre_check
    ;;
    
  *)
    echo "Usage: $0 {stop|start|restart}"
    false
    ;;
esac
exit $?
