ifneq ($(BR2_LRD_DEVEL_BUILD),y)

WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION = $(call qstrip,$(BR2_PACKAGE_WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION_VALUE))
WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_SOURCE =
WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_LICENSE = GPL-2.0
WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS = summit_supplicant-arm-eabihf-$(WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION).tar.bz2

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_SITE = http://devops.lairdtech.com/share/builds/linux/summit_supplicant/laird/$(WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION)
else
  WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_SITE = https://github.com/LairdCP/wb-package-archive/releases/download/LRD-REL-$(WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION)
endif

define WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_INSTALL_TARGET_CMDS
	tar -xjf $($(PKG)_DL_DIR)/$(WB50SYSD_SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch
endef

endif

$(eval $(generic-package))
