#!/bin/ash

# Copyright (c) 2020, Laird Connectivity
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: support@lairdconnect.com

# fips-set - set different fips mode

usage() {
  cat <<- usage-info-block
Toggle the fips=0/1 and fips_wifi=0/1 portion of the uboot env bootargs
Usage example:
To set fips
# fips-set fips
To set fips and fips_wifi
# fips-set fips_wifi
To unset fips and fips_wifi
# fips-set unset
usage-info-block
}

warning() {
  echo "Changes will take effect after reboot"
}

parse_flag() {
  case $1 in
    -h|--help) ## show usage
      usage
      ;;
    fips) ## set fips only
      fw_setenv fips_wifi
      fw_setenv fips 1
      warning
      ;;
    fips_wifi) ## set fips wifi
      fw_setenv fips 1
      fw_setenv fips_wifi 1
      warning
      ;;
    unset) ## unset
      fw_setenv fips
      fw_setenv fips_wifi
      warning
      ;;
    *) ## break
      return 1
  esac
}

parse_flag $1
