#!/bin/sh
# proftpd - ftp daemon init-script
# supports inetd and pre-checking configuration

[ ! -d /var/run/proftpd ] && mkdir /var/run/proftpd
[ ! -f /var/log/wtmp ] && touch /var/log/wtmp


pre_check() {
  test -s /etc/proftpd.conf \
    || { on_error="-- proftpd.conf file n/a"; return 1; }

  # run via inetd
  if [ -n "$inetd_" ]
  then
    # set ServerType to "inetd" if necessary
    grep -q '^ServerType[[:space:]]\+standalone' /etc/proftpd.conf \
    && sed '/^ServerType/s/standalone/inetd/' -i /etc/proftpd.conf \
    && fsync /etc/proftpd.conf
  else
    # set ServerType to "standalone" if necessary
    grep -q '^ServerType[[:space:]]\+inetd' /etc/proftpd.conf \
    && sed '/^ServerType/s/inetd/standalone/' -i /etc/proftpd.conf \
    && fsync /etc/proftpd.conf
  fi
  return 0
}

case "$1" in
  stop)
    echo -n "Stopping ProFTPd "
    killall proftpd 2>/dev/null
    echo "-OK"
    ;;

  start)
    echo -n "Starting ProFTPd "
    test -z "$rcS_" \
      && pre_check

    if [ $? -eq 0 ] \
    && /usr/sbin/proftpd
    then
      echo "-OK"
    else
      echo "-FAILED ${on_error}"
      false
    fi
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  check)
    pre_check || { echo "${0##*/} $1 ${on_error}"; false; }
    ;;

  *)
    echo "Usage: $0 {stop|start|restart|check}"
    false
	 ;;
esac
exit $?
