#!/bin/sh

test -r /etc/default/usb-gadget && . /etc/default/usb-gadget

case "${1}" in
	start)
		/usr/bin/usb-gadget.sh start "${USB_GADGET_ETHER}" "${USB_GADGET_SERIAL_PORTS}"
		;;

	stop)
		/usr/bin/usb-gadget.sh stop
		;;

	restart|reload)
		/usr/bin/usb-gadget.sh stop
		/usr/bin/usb-gadget.sh start "${USB_GADGET_ETHER}" "${USB_GADGET_SERIAL_PORTS}"
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
