#!/bin/sh

case "${1}" in
	start)
		/usr/bin/usb-gadget.sh start
		;;

	stop)
		/usr/bin/usb-gadget.sh stop
		;;

	restart|reload)
		/usr/bin/usb-gadget.sh stop
		/usr/bin/usb-gadget.sh start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
