#!/bin/sh

proto=

case "$1" in
	start)
		/usr/bin/usb-gadget.sh start ${proto}
		;;

	stop)
		/usr/bin/usb-gadget.sh stop ${proto}
		;;

	restart|reload)
		/usr/bin/usb-gadget.sh stop ${proto}
		/usr/bin/usb-gadget.sh start ${proto}
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
