ifneq ($(BR2_LRD_DEVEL_BUILD),y)

BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_VERSION = $(call qstrip,$(BR2_PACKAGE_LRD_RADIO_STACK_VERSION_VALUE))
BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_SOURCE =
BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_LICENSE = GPL-2.0
BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_INSTALL_STAGING = YES

BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS = summit_supplicant_legacy-arm-eabi-$(BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_VERSION).tar.bz2

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_SITE = https://files.devops.rfpros.com/builds/linux/summit_supplicant/laird/$(BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_VERSION)
else
  BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_SITE = https://github.com/LairdCP/wb-package-archive/releases/download/LRD-REL-$(BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_VERSION)
endif

define BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_INSTALL_STAGING_CMDS
	tar -xjf $($(PKG)_DL_DIR)/$(BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS) -C $(STAGING_DIR) --keep-directory-symlink --no-overwrite-dir --touch --wildcards usr/include usr/lib/lib*
endef

define BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_INSTALL_TARGET_CMDS
	tar -xjf $($(PKG)_DL_DIR)/$(BR2_PACKAGE_WB_LEGACY_SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch --exclude=usr/include --exclude=usr/lib/libsdc_sdk.so
endef

endif

$(eval $(generic-package))
