ifneq ($(BR2_LRD_DEVEL_BUILD),y)

WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION = $(call qstrip,$(BR2_PACKAGE_LRD_RADIO_STACK_VERSION_VALUE))
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_SOURCE =
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_LICENSE = GPL-2.0

ifeq ($(BR2_LRD_WB50N_SYSD_FIPS_RADIO),y)
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE1 = _fips
else ifeq ($(BR2_PACKAGE_LIBOPENSSL_1_0_2),y)
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE1 = _openssl_1_0_2
else
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE1 =
endif

ifeq ($(BR2_TOOLCHAIN_EXTERNAL_LAIRD_ARM),y)
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE2 = -arm-eabihf
else ifeq  ($(BR2_TOOLCHAIN_EXTERNAL_LAIRD_AARCH64),y)
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE2 = -aarch64-eabihf
else
# default to -arm-eabihf
WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE2 = -arm-eabihf
endif

WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS = summit_supplicant$(WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE1)$(WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_TYPE2)-$(WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION).tar.bz2

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_SITE = https://files.devops.rfpros.com/builds/linux/summit_supplicant/laird/$(WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION)
else
  WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_SITE = https://github.com/LairdCP/wb-package-archive/releases/download/LRD-REL-$(WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_VERSION)
endif

define WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_INSTALL_TARGET_CMDS
	tar -xjf $($(PKG)_DL_DIR)/$(WB50N_SYSD_SUMMIT_SUPPLICANT_BINARIES_EXTRA_DOWNLOADS) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch
endef

endif

$(eval $(generic-package))
