#!/bin/sh
# sshd init-script
# supports inetd and pre-checking configuration

check_configuration() {
  echo "Checking sshd configuration..."
  
  # Make sure the ssh-keygen progam exists
  [ -x /usr/bin/ssh-keygen ] || { echo "  ...missing ssh-keygen"; exit 1; }

  # Check that the sshd_config file exists
  [ -f /etc/ssh/sshd_config ] || { echo "  ...missing sshd_config"; exit 1; }

  # See if need to generate the SSH1 RSA key
  if [ ! -s /etc/ssh/ssh_host_key ] \
  && grep -q "^HostKey.*host_key" /etc/ssh/sshd_config
  then
    echo Generating RSA Key...
    /usr/bin/ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key~ -C '' -N '' \
    && {
      mv -f /etc/ssh/ssh_host_key~.pub /etc/ssh/ssh_host_key.pub
      mv -f /etc/ssh/ssh_host_key~ /etc/ssh/ssh_host_key
    }
  fi

  # See if need to generate the SSH2 RSA key
  if [ ! -s /etc/ssh/ssh_host_rsa_key ] \
  && grep -q "^HostKey.*host_rsa_key" /etc/ssh/sshd_config
  then
    echo Generating RSA Key...
    /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key~ -C '' -N '' \
    && {
      mv -f /etc/ssh/ssh_host_rsa_key~.pub /etc/ssh/ssh_host_rsa_key.pub
      mv -f /etc/ssh/ssh_host_rsa_key~ /etc/ssh/ssh_host_rsa_key
    }
  fi

  # See if need to generate the SSH2 DSA key
  if [ ! -s /etc/ssh/ssh_host_dsa_key ] \
  && grep -q "^HostKey.*host_dsa_key" /etc/ssh/sshd_config
  then
    echo Generating DSA Key... \(may take awhile\)
    /usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key~ -C '' -N '' \
    && {
      mv -f /etc/ssh/ssh_host_dsa_key~.pub /etc/ssh/ssh_host_dsa_key.pub
      mv -f /etc/ssh/ssh_host_dsa_key~ /etc/ssh/ssh_host_dsa_key
    }
  fi

  # See if need to generate the SSH2 ECDSA key
  if [ ! -s /etc/ssh/ssh_host_ecdsa_key ] \
  && grep -q "^HostKey.*host_ecdsa_key" /etc/ssh/sshd_config
  then
    echo Generating ECDSA Key... \(may take awhile\)
    /usr/bin/ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key~ -C '' -N '' \
    && {
      mv -f /etc/ssh/ssh_host_ecdsa_key~.pub /etc/ssh/ssh_host_ecdsa_key.pub
      mv -f /etc/ssh/ssh_host_ecdsa_key~ /etc/ssh/ssh_host_ecdsa_key
    }
  fi
}                

umask 077

case "$1" in
  check)
    # inetd pre-check support
    # Ror each enabled key type in config, the respective keyfile is checked to
    # exist and be greater than zero size. The key pair are regenerated w/temp
    # names and upon completion, renamed to respective names.
    check_configuration
    ;;
  stop)
    echo -n "Stopping sshd: "
    killall sshd 2>/dev/null
    #rm -f /var/lock/sshd.lock
    echo "OK" 
    ;;
  start)
    # always check config if running manually
    [ -z "$rcS_" ] && check_configuration
    echo -n "Starting sshd: "
    /usr/sbin/sshd
    #touch /var/lock/sshd.lock
    echo "OK"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {stop|start|restart}"
    false
esac
exit $?
