#!/bin/sh

[ -f /usr/bin/deviced ] || exit 0

case "$1" in
        start)
                printf "Starting deviced: "
		python /usr/bin/deviced
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        stop)
                printf "Stopping deviced: "
		kill `ps -o user,pid,args | grep -v grep | grep deviced | awk '{ print $2 }'`
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        restart|reload)
                $0 stop
                $0 start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit 0

