ifneq ($(BR2_LRD_DEVEL_BUILD),y)

WB45N_FIRMWARE_BINARIES_VERSION = $(call qstrip,$(BR2_PACKAGE_LRD_RADIO_STACK_VERSION_VALUE))
WB45N_FIRMWARE_BINARIES_SOURCE =
WB45N_FIRMWARE_BINARIES_LICENSE = GPL-2.0
WB45N_FIRMWARE_BINARIES_LICENSE_FILES = COPYING
WB45N_FIRMWARE_BINARIES_EXTRA_DOWNLOADS = laird-ath6k-6003-firmware-$(WB45N_FIRMWARE_BINARIES_VERSION).tar.bz2

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  WB45N_FIRMWARE_BINARIES_SITE =  https://files.devops.rfpros.com/builds/linux/firmware/$(WB45N_FIRMWARE_BINARIES_VERSION)
else
  WB45N_FIRMWARE_BINARIES_SITE = https://github.com/LairdCP/wb-package-archive/releases/download/LRD-REL-$(WB45N_FIRMWARE_BINARIES_VERSION)
endif

define WB45N_FIRMWARE_BINARIES_INSTALL_TARGET_CMDS
	tar -xjf $($(PKG)_DL_DIR)/laird-ath6k-6003-firmware-$(WB45N_FIRMWARE_BINARIES_VERSION).tar.bz2 -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch
endef

endif

$(eval $(generic-package))
