#!/bin/sh

# Copyright (c) 2018, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: ews-support@lairdtech.com

# bootoverlay - mount extra OverlayFSes
# Add any extra overlayfs mounts to this script

case $1 in

  stop)
    if ! touch /.rw 2>/dev/null
    then
	umount /home
    fi
    ;;

  start)
    if ! touch /.rw 2>/dev/null
    then
	mkdir -p /mnt/home-upperdir
        mkdir -p /mnt/home-workdir
        mount -t overlay -olowerdir=/home,upperdir=/mnt/home-upperdir,workdir=/mnt/home-workdir overlayfs /home
     fi
    ;;
esac
exit 0

